Error Stack Experiment
real-logic/aeron pull request #1099
Opened 2020-12-04 02:36 UTC by mikeb01

More for discussion that immediate merge.  This introduces a different approach for handling errors and capturing context as we traverse the stack.  The idea being that if an error occurs, we set the error similar to normal, with an error code and a formatted message.  As we return back up through the stack, when it looks like a call further down has caused the error, then we can append additional context to the current error stack.  Adds 2 macros:
- `AERON_SET_ERROR(error_code, format, ...)`
- `AERON_APPEND_ERROR(format, ...)`

`AERON_SET_ERROR` should be used at the edge of the Aeron driver (or client), when we have tried to do something and it has failed.  E.g. system call or some internal validation.  At this point we set the error code and and capture any immediate context relevant data.  This call will also reset the error stack discarding any previously captured messages.

`AERON_APPEND_ERROR` is used when another Aeron function has returned `-1` in which case we just append some local context to the error stack and return `-1` again.  This allow for additional context information to be included in the error message without having to pass that information up or down the stack and break encapsulation for the purposes of error reporting.

I've demonstrated how this would work for initialising the UDP channel transport.  On failure the error message reporting back to the client ends up being:
```
io.aeron.exceptions.RegistrationException: ERROR - (98) Address already in use
[aeron_udp_channel_transport_init, aeron_udp_channel_transport.c:85] unicast bind(127.0.0.1:24325)
[aeron_receive_destination_create, aeron_receive_destination.c:55] uri = aeron:udp?endpoint=localhost:24325
[aeron_driver_conductor_get_or_add_receive_channel_endpoint, aeron_driver_conductor.c:1644] correlation_id = 3
```
Similarly the distinct error log ends up containing:
```
1 observations from 2020-12-04 15:31:41.855+1300 to 2020-12-04 15:31:41.855+1300 for:
 0: (98) Address already in use
[aeron_udp_channel_transport_init, aeron_udp_channel_transport.c:85] unicast bind(127.0.0.1:24325)
[aeron_receive_destination_create, aeron_receive_destination.c:55] uri = aeron:udp?endpoint=localhost:24325
[aeron_driver_conductor_get_or_add_receive_channel_endpoint, aeron_driver_conductor.c:1644] correlation_id = 2
```
I've limited the depth of the stack to 16.  If it overflows, then we track the lowest 15 elements of the error stack and the highest one.  When dumping out the stack we would potentially see something similar to:
```
[TestBody, aeron_error_test.cpp:70] this is the root error
[TestBody, aeron_error_test.cpp:73] this is a nested error: 0
[TestBody, aeron_error_test.cpp:73] this is a nested error: 1
[TestBody, aeron_error_test.cpp:73] this is a nested error: 2
[TestBody, aeron_error_test.cpp:73] this is a nested error: 3
[TestBody, aeron_error_test.cpp:73] this is a nested error: 4
[TestBody, aeron_error_test.cpp:73] this is a nested error: 5
[TestBody, aeron_error_test.cpp:73] this is a nested error: 6
[TestBody, aeron_error_test.cpp:73] this is a nested error: 7
[TestBody, aeron_error_test.cpp:73] this is a nested error: 8
[TestBody, aeron_error_test.cpp:73] this is a nested error: 9
[TestBody, aeron_error_test.cpp:73] this is a nested error: 10
[TestBody, aeron_error_test.cpp:73] this is a nested error: 11
[TestBody, aeron_error_test.cpp:73] this is a nested error: 12
[TestBody, aeron_error_test.cpp:73] this is a nested error: 13
(11 lines omitted...)
[TestBody, aeron_error_test.cpp:73] this is a nested error: 25
```
So the error message would inform any user that some of the stack elements had to be omitted.  I think 16 should be plenty.  Our call stacks a pretty shallow.

2020-12-06 18:56 UTC, mjpt777 commented
I really like this. So useful to build up context.

2020-12-22 03:35 UTC, mikeb01 commented
I think this is good to go now.  I've ended up doing a fair overhaul of the error reporting in the C driver and client.  I've simplified the way that the distinct error log reporter works in the C driver and it is more like the Java implementation.  I.e. it matches against the shape of the stack trace (with the C driver it is just a string comparison).  It also decouples cleanly the formatting of error messages from the recording of them.  As a result I've updated a lot of the top of stack reporting in the conductor, sender and receiver.

I've also simplified the implementation of the error reporting itself.  It no longer maintains a stack, just a single buffer.  This reduces some of the headaches when the output of a error stack from the server gets embedded in an error line for the client.  Now there is less chance of truncation.

2020-12-23 10:42 UTC, mjpt777 commented on aeron-client/src/main/c/aeron_alloc.c
> +        AERON_SET_ERR(ENOMEM, "Failed to allocate %llu bytes", (unsigned long long)size);
Would it be better to cast to `uint64_t` and use `PRI` macro?

2020-12-23 10:45 UTC, mjpt777 commented on aeron-client/src/main/c/aeron_exclusive_publication.c
> +            (unsigned long long)address_vec_len);
Better to use fix length types.

2020-12-23 10:46 UTC, mjpt777 commented on aeron-client/src/main/c/aeron_publication.c
> +            EINVAL, "Parameters must be valid, address_vec_len (%llu) < 1", (unsigned long long) address_vec_len);
Better to use fixed length types.

2020-12-23 10:47 UTC, mjpt777 commented on aeron-client/src/main/c/aeron_subscription.c
> +        AERON_APPEND_ERR("Unable to allocate image list, length: %lld", (unsigned long long)length);
Better to use fixed length types.

2020-12-23 10:47 UTC, mjpt777 commented on aeron-client/src/main/c/aeron_subscription.c
> +            EINVAL, "Parameters must be valid, address_vec_len (%llu) < 1", (unsigned long long) address_vec_len);
Better to use fixed length types.

2020-12-23 10:47 UTC, mjpt777 commented on aeron-client/src/main/c/aeron_subscription.c
> +            EINVAL, "Parameters must be valid, address_len (%llu) < 1", (unsigned long long) address_len);
Better to use fixed length types.

2020-12-23 10:47 UTC, mjpt777 commented on aeron-client/src/main/c/aeron_subscription.c
> +            EINVAL, "Parameters must be valid, uri_len (%llu) < 1", (unsigned long long) uri_len);
Better to use fixed length types.

2020-12-23 10:48 UTC, mjpt777 commented on aeron-client/src/main/c/concurrent/aeron_broadcast_receiver.c
> +        AERON_SET_ERR(EINVAL, "Capacity: %llu invalid, must be power of two", (unsigned long long) capacity);
Better to use fixed length types.

2020-12-23 10:48 UTC, mjpt777 commented on aeron-client/src/main/c/concurrent/aeron_broadcast_receiver.c
> +                "unable to keep up with broadcast, last_seen_lapped_count: %ld, receiver->lapped_count: %ld",
Better to use fixed length types.

2020-12-23 10:49 UTC, mjpt777 commented on aeron-client/src/main/c/concurrent/aeron_broadcast_receiver.c
> +                (unsigned long long) sizeof(receiver->scratch_buffer));
Better to use fixed length types.

2020-12-23 10:49 UTC, mjpt777 commented on aeron-client/src/main/c/concurrent/aeron_broadcast_transmitter.c
> +        AERON_SET_ERR(EINVAL, "Capacity: %llu invalid, must be power of two", (unsigned long long) capacity);
Better to use fixed length types.

2020-12-23 10:49 UTC, mjpt777 commented on aeron-client/src/main/c/concurrent/aeron_counters_manager.c
> +            (unsigned long long)metadata_length,
Better to use fixed length types.

2020-12-23 10:59 UTC, mjpt777 requested changes
LGTM

2021-02-02 19:53 UTC, merged